services:
  app:
    build: .
    container_name: logpulse-app
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      SIM_BASE_URL: http://app:8000
      SIM_ENABLED: "true"
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    networks:
      - logpulse

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: logpulse-otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    depends_on:
      - elasticsearch
    networks:
      - logpulse

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: logpulse-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      logpulse:
        aliases:
          - elasticsearch

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: logpulse-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - otel-collector
    networks:
      logpulse:
        aliases:
          - prometheus

  nginx:
    image: nginx:1.25-alpine
    container_name: logpulse-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - elasticsearch
      - prometheus
    networks:
      - logpulse

volumes:
  es_data:

networks:
  logpulse:
